CREATE TABLE news
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    author  VARCHAR(255),
    title   VARCHAR(255),
    content TEXT,
    CONSTRAINT pk_news PRIMARY KEY (id)
);

insert into news(author, title, content)
values ('Bob', 'Shiba Inu',
        'The Shiba Inu is the smallest of the six original and distinct spitz breeds of dog from Japan. A small, agile dog that copes very well with mountainous terrain, the Shiba Inu was originally bred for hunting.'),
       ('Bill', 'Shiba Inu',
        'The Shiba Inu is the smallest of the six original and distinct spitz breeds of dog from Japan. A small, agile dog that copes very well with mountainous terrain, the Shiba Inu was originally bred for hunting.'),
       ('Henry', 'Shiba Inu',
        'The Shiba Inu is the smallest of the six original and distinct spitz breeds of dog from Japan. A small, agile dog that copes very well with mountainous terrain, the Shiba Inu was originally bred for hunting.'),
       ('Vong', 'Shiba Inu',
        'The Shiba Inu is the smallest of the six original and distinct spitz breeds of dog from Japan. A small, agile dog that copes very well with mountainous terrain, the Shiba Inu was originally bred for hunting.'),
       ('Misha', 'truest',
        'The Shiba Inu is the smallest of the six original and distinct spitz breeds of dog from Japan. A small, agile dog that copes very well with mountainous terrain, the Shiba Inu was originally bred for hunting.');